### ISSUE TITLE
BE: Polishing for MVP.

### ISSUE THREAD

**Issue by SoySauceLabs** [Plantalytics/plantalytics-backend#12]
# TODO's:
- [x] Handle database **exceptions** via general error handling && error responses.
- [x] Improve **unit tests**.
- [x] Link **login endpoint** to database.
