### ISSUE TITLE
BE: Housekeeping Grab Bag 08/08

### ISSUE THREAD

**Issue by SoySauceLabs** [Plantalytics/plantalytics-backend#46]
# TODOs Prior to Admin API Implementation:
- [x] Extract existing unit tests into "endpoint associated" files. ✂️ 
- [x] Add new unit tests to increase code coverage. 📈 
- [x] Determine solution to Travis "limit" on number of encrypted env vars. 🔢 
- [x] Add more encrypted env vars. 🔣  
- [x] Clean up code to PEP8 Standard. 📝 
- [x] Readme updates. 📚 
- [x] Add health check endpoint. 🏥 
- [x] Add PUT to supported methods on `/hub_data` endpoint. 👐 
- [x] The kitchen sink (i.e. Refactoring - you get a refactor, and _you_ get a refactor!!). 🛁
